version: '3.8'
services:
  app:
    container_name: ffmpeg-node
    build: .
    ports:
      - 8080:3000
      - 8082:3002
      - 8083:4000
      - 8084:4001
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      # - .aws/:/root/.aws:delegated
      - .:/app
      - node_modules:/app/node_modules
    command: ash -c 'npm install && /bin/ash'

volumes:
  node_modules: