export const MOVE_ENUM = Object.freeze({
  PAN_LEFT: "PAN_LEFT",
  PAN_RIGHT: "PAN_RIGHT",
  PAN_UP: "PAN_UP",
  PAN_DOWN: "PAN_DOWN",
  PAN_TOP_LEFT: "PAN_TOP_LEFT",
  PAN_TOP_RIGHT: "PAN_TOP_RIGHT",
  PAN_BOTTOM_LEFT: "PAN_BOTTOM_LEFT",
  PAN_BOTTOM_RIGHT: "PAN_BOTTOM_RIGHT",
});
