export const POSITION_ENUM = Object.freeze({
  CENTER: "CENTER",
  TOP: "TOP",
  TOP_LEFT: "TOP_LEFT",
  TOP_RIGHT: "TOP_RIGHT",
  TOP_CENTER: "TOP_CENTER",
  BOTTOM: "BOTTOM",
  BOTTOM_LEFT: "BOTTOM_LEFT",
  BOTTOM_RIGHT: "BOTTOM_RIGHT",
  BOTTOM_CENTER: "BOTTOM_CENTER",
  RIGHT_CENTER: "RIGHT_CENTER",
  LEFT_CENTER: "LEFT_CENTER",
});
