export const ZOOM_ENUM = Object.freeze({
  IN: "IN",
  OUT: "OUT",

  //TODO test
  IN_PAN_UP: "IN_PAN_UP",
  IN_PAN_DOWN: "IN_PAN_DOWN",
  IN_PAN_TOP_LEFT: "IN_PAN_TOP_LEFT",
  IN_PAN_TOP_RIGHT: "IN_PAN_TOP_RIGHT",
  IN_PAN_BOTTOM_LEFT: "IN_PAN_BOTTOM_LEFT",
  IN_PAN_BOTTOM_RIGHT: "IN_PAN_BOTTOM_RIGHT",
  OUT_PAN_UP: "OUT_PAN_UP",
  OUT_PAN_DOWN: "OUT_PAN_DOWN",
  OUT_PAN_TOP_LEFT: "OUT_PAN_TOP_LEFT",
  OUT_PAN_TOP_RIGHT: "OUT_PAN_TOP_RIGHT",
  OUT_PAN_BOTTOM_LEFT: "OUT_PAN_BOTTOM_LEFT",
  OUT_PAN_BOTTOM_RIGHT: "OUT_PAN_BOTTOM_RIGHT",
});
